# Generated by Django 5.2.8 on 2025-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='detailed_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='short_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
