# Generated by Django 5.2.8 on 2025-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_summaryhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryhistory',
            name='summary_text',
        ),
        migrations.RemoveField(
            model_name='summaryhistory',
            name='summary_tokens',
        ),
        migrations.AddField(
            model_name='summaryhistory',
            name='detailed_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summaryhistory',
            name='short_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
