# Generated by Django 5.2.8 on 2026-03-01 17:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_summaryhistory_summary_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='documents_d_search__2b9c37_gin'),
        ),
    ]
