# Generated by Django 5.2.8 on 2026-03-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentchunk_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
